services:
  Llama-SEA-LION-v3-8B-IT:
    image: ghcr.io/huggingface/text-generation-inference:3.2.3
    container_name: Llama-SEA-LION-v3-8B-IT
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - tgi-data:/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command: [
      "--json-output",
      "--quantize", "bitsandbytes-nf4",
      "--max-input-tokens", "256",
      "--max-batch-prefill-tokens", "512",
      "--model-id", "aisingapore/Llama-SEA-LION-v3-8B-IT"
    ]

volumes:
  tgi-data:
